"""empty message

Revision ID: 5111e3ee3f5f
Revises: a9ab9b0c0190
Create Date: 2025-01-08 21:05:27.200692

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5111e3ee3f5f'
down_revision = 'a9ab9b0c0190'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('street', sa.String(length=80), nullable=False))
        batch_op.add_column(sa.Column('city', sa.String(length=80), nullable=False))
        batch_op.add_column(sa.Column('country', sa.String(length=80), nullable=False))
        batch_op.alter_column('address',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('address',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)
        batch_op.drop_column('country')
        batch_op.drop_column('city')
        batch_op.drop_column('street')

    # ### end Alembic commands ###
